### ISSUE TITLE
如果缓存的数据有修改需求，最佳实践是什么？

### ISSUE THREAD

**Issue by Cloud33** [orca-zhang/ecache#9]
存放对象 or 指针（深拷贝后在副本上修改）？

修改的次数比较多，对象结构复杂（对象有三四层）

**Comment by orca-zhang** [comment]
深拷贝是最朴素的做法，相对来说消耗比较大，对于比较大的对象来说，和bigcache、freecache用法就接近了，体现不出ecache的优势。

更好的方案是，如果再上层涉及到协议层传输转换的话，比如使用pb、json、form-data等，也可以考虑到这一层加缓存，并且对有差异的部分打补丁（补丁部分也可以单独缓存），也就是在快发出去之前做数据组装和修订即可。

**Comment by Cloud33** [comment]
明白，谢谢
